# Generated by Django 5.0 on 2023-12-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='medial_department',
        ),
        migrations.AddField(
            model_name='doctor',
            name='medial_department',
            field=models.ManyToManyField(related_name='doctors', to='hospitals.medicaldepartment'),
        ),
    ]
