# Generated by Django 5.0 on 2023-12-15 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='end_lunch_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='start_lunch_time',
            field=models.TimeField(blank=True, default=datetime.time(11, 0), null=True),
        ),
    ]
