# Generated by Django 5.0 on 2023-12-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_businesshours_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], db_index=True, max_length=10),
        ),
    ]
